version: "3.3"

services:

  nginx_demo:
    image: "nginx"
    container_name: "service_nginx_demo"
    restart: always
    ports:
      - 80:80


networks:
  default:
    external: true
    name: bridge_frontend
